#!/bin/bash

# Author: André Santos
# Date Created: 31/03/2025
# Last Modified: 31/03/2025

# Description: 
# Creates a backup in ~/bash_course folder of all files in the home directory

# Usage:
# backup_script

echo "Backuping home directory" 

tar -cvf ~/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
exit 0
