#!/bin/bash

# Author: André Santos
# Date Created: 31/03/2025
# Last Modified: 31/03/2025

# Description: 
# Creates a backup in ~/bash_course folder of all files in the home directory

# Usage:
# backup_script

echo "Hello, ${USER^}"
echo "I will now back up your home directory, $HOME"

currentdir=$(pwd)

echo "You are running this script from $currentdir."
echo "Therefore, I will save the backup in $currentdir."

tar -cf "$currendir_$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null

echo "Backup Completed Successfully"
exit 0
