#!/bin/bash

# Author: André Santos
# Date Created: 28/03/2025
# Last Modified: 28/03/2025

# Description: 
# Print "this is my first script" to the terminal

# Usage
# our_first_script 

echo "this is my first script"
exit 0
